Feature/erb 11 hero logic
FooCamp/foocamp-escuela-robotica pull request #2
Opened 2021-08-18 02:09 UTC by sofiaperezm

# FooCamp - Escuela de Robotica

## Trello ticket
[Ticket Link](https://trello.com/c/XHnqCLj3/23-user-story-11-hero-logic)

## Description
- Se agregó el archivo temporal `templates/hero-temp.html` que contiene los elementos básicos del hero, dicho archivo es usado sólo con el propósito de probar la lógica del carrusel y será remplazado por el output del [Ticket 10](https://trello.com/c/FcUXOy7G/14-user-story-02-homehero).
- Se agregó el archivo `src/scss/components/carousel.scss` que contiene los estilos básicos aplicados al carousel (similar al ítem anterior, se trata de un archivo temporal).
- Se modificó el archivo `src/scss/_component.scss` para importar el archivo del item anterior. 
- Se agregó el archivo `src/js/carousel.js` que contiene la lógica del carousel.
- Se modificó el archivo `src/js/app.js` para importar el archivo del item anterior. 

## To reproduce

1. Correr el proyecto.
2. Abrir la página http://localhost:8080/templates/hero-temp.html
3. Revisar las 2 funcionalidades del carrousel, **A.** el auto-play y **B.** la selección de un slider específico del carousel. 

## Screenshots
En el siguiente screenshot se puede notar que el slider visible es el primero, que corresponde con la clase `active` en el elemento HTML button dentro del div con la clase `dots-list`.

![slider_1_active](https://user-images.githubusercontent.com/32691511/129824726-1a17a393-c972-466e-ae31-57290df4b18f.png)

Similar al anterior screenshot, se puede notar que el slider visible ahora es el tercero. 

![slider_3_active](https://user-images.githubusercontent.com/32691511/129824897-a8d61ac0-18ca-436b-ad2e-c1de2fa1cc48.png)

2021-08-23 18:47 UTC, camilomejiag reviewed
I really like the implementation, but this will only work when there are 4 images. If the client decides to use 3 or 5, it may not work. Try using a variable instead of the `3` on `line 8`, and see what can be improved there.

`currentIndex = currentIndex === numberOfPages ? 0 : currentIndex + 1;`

2021-08-23 18:47 UTC, camilomejiag commented on src/scss/components/carousel.scss
> +	flex-shrink: 0;
Please check the indentation on the different elements to be consistent. As well as the spacing between the different elements. Some have 1 space in between, other have 2

2021-08-23 18:47 UTC, camilomejiag commented on src/scss/components/carousel.scss
> +    background-color: #8894B4;
Please add the colors on the variables scss file

2021-08-28 14:34 UTC, diegoamt requested changes

2021-08-28 14:34 UTC, diegoamt commented on src/js/carousel.js
> +const carousel = document.querySelector(".carousel");
tip: use $carousel or carouselEl to know when a variable references to a DOM element.

2021-08-28 14:34 UTC, diegoamt commented on src/js/carousel.js
> +for (let i = 0; i < dots.length; i++) {
tip: you can use forEach `dots.forEach($dot => $dot.addEventListener("click", onClickDot))`

2021-08-28 14:34 UTC, diegoamt commented on src/js/carousel.js
> +  slider.style.transition = ".7s";
you can avoid adding this inline style with js. Pleas add on _carousel.scss_ `transition: transform .7s ease; ` for the .slider selector.

2021-08-28 14:34 UTC, diegoamt commented on src/js/carousel.js
> +const onClickDot = (event) => {
I see here the same logic as the setInterval function (auto-play logic). You should create a function like `const showSlide = (index) => { ... }`. we don't want to repeat code.

2021-09-01 23:53 UTC, camilomejiag approved these changes

2021-09-02 22:10 UTC, diegoamt approved these changes

2021-09-03 03:47 UTC, merged