enhancement/ERC-responsive-header
FooCamp/foocamp-escuela-robotica pull request #23
Opened 2021-10-07 04:57 UTC by sofiaperezm

# FooCamp - Escuela de Robotica

## Trello ticket
[Enhancement: Responsive en Header](https://trello.com/c/Eb8iRb3i/37-enhancement-responsive-en-header)

## Description

1. Added the collapsing navigation menu component in the header in the `templates/header.hbs` file
2. Added functionality to handle the collapsing navigation menu in the `src/js/handleBurgerMenu.js` file
3. Added the corresponding media queries in `src/scss/layout/_header.scss` file in order to apply responsive design. 

## To reproduce

1. Run the project
2. Open the `http://localhost:8080` page 
3. Check the header component, especially in the small viewports.
4. Interact with the burger menu icon

## Screenshot

Burger menu icon in small viewport
![Captura de Pantalla 2021-10-06 a la(s) 11 37 02 p  m](https://user-images.githubusercontent.com/32691511/136322343-b6b0db0b-04af-49fc-8260-accadde291f0.png)
s

Collapsing navigation menu open in small viewport
![Captura de Pantalla 2021-10-06 a la(s) 11 37 13 p  m](https://user-images.githubusercontent.com/32691511/136322416-18d34a4b-8dc1-406d-9848-7cb01d0b1423.png)

The collapsing navigation menu feature in action

https://user-images.githubusercontent.com/32691511/136322600-890adc19-b98a-481c-8226-888dda8cacf3.mp4

2021-10-07 05:48 UTC, diegoamt requested changes

2021-10-07 05:48 UTC, diegoamt commented on templates/header.hbs
> +        <div class="header__menu">
tip: I suggest a better class name like `header__mobile-menu` or similar.

2021-10-07 05:48 UTC, diegoamt commented on templates/header.hbs
> +            <ul class="links__menu">
following BEM, you should use a class like `header__<block>`. Please replace this class by `header__mobile-links` or similar.

2021-10-07 05:48 UTC, diegoamt commented on templates/link.hbs
> +<li class="header__item"><a class="header__link" href={{linkDestination}}>{{linkText}}</a></li>
use `href="{{ url }}"` instead of `href={{linkDestination}}`

2021-10-07 05:48 UTC, diegoamt commented on templates/header.hbs
> +            <span class="icon close__icon">✕</span>
please use a different class following BEM, like header__close-icon

2021-10-12 00:54 UTC, diegoamt approved these changes

2021-10-15 22:10 UTC, closed without merging

2021-10-15 22:11 UTC, sofiaperezm commented
Please check duplicate  on [PR 27](https://github.com/FooCamp/foocamp-escuela-robotica/pull/27)