Feature/pie de pagina
FooCamp/foocamp-escuela-robotica pull request #3
Opened 2021-08-18 23:09 UTC by clmtest

# FooCamp - Escuela de Robotica

## Trello ticket
[Ticket Link](https://trello.com/c/lsLgPpW6/12-user-story-10-pie-de-p%C3%A1gina)

## Description
This PR contains the HTML and SCSS files for the pie-de-pagina of the Escuela de Robotica 

## To reproduce
1. Run the project with the following command line: npm run dev
2. Open the following page: http://localhost:8080/christian-page.html
3. Check the component

## Screenshots
<img width="1076" alt="Footer" src="https://user-images.githubusercontent.com/62309068/129983408-1c991425-5a85-4e2a-bd41-94a58e011f2c.png">

2021-08-23 18:39 UTC, camilomejiag requested changes

2021-08-23 18:39 UTC, camilomejiag commented on src/scss/layout/_footer.scss
> +    background-color: #577598;
Please make this color part of the variables on the sass files

2021-08-23 18:39 UTC, camilomejiag commented on src/scss/layout/_footer.scss
> +
Remove one of the extra spaces here

2021-08-23 18:39 UTC, camilomejiag commented on src/scss/layout/_footer.scss
> +    &__section--row{
This query can be inside the `&__section` one.
You can do something like
```
&__section {
   &--row {
   
   }
}
```

2021-08-23 18:39 UTC, camilomejiag commented on src/scss/layout/_footer.scss
> +        color: #FFFFFF;
color on the variable file

2021-08-23 18:39 UTC, camilomejiag commented on src/scss/layout/_footer.scss
> +    max-width: 1440px;
Please define this on a higher level. The max width of the footer is not only on this component, but the whole application

2021-08-23 18:39 UTC, camilomejiag commented on src/scss/layout/_footer.scss
> +        color: #FFFFFF;
color in the variable file

2021-08-23 18:39 UTC, camilomejiag commented on src/scss/layout/_footer.scss
> +        color: #FFFFFF;
color in the variable file

2021-08-23 18:39 UTC, camilomejiag commented on src/scss/layout/_footer.scss
> +        color: #FFFFFF;
color in the variable file

2021-08-23 18:39 UTC, camilomejiag commented on src/scss/layout/_footer.scss
> +        color: #2C8EFF;
color in the variable file

2021-08-23 18:39 UTC, camilomejiag commented on src/scss/layout/_footer.scss
> +        width: 26.05px;
Some browsers don't recognize decimal on pixels. Please keep them as integers.

2021-08-23 18:39 UTC, camilomejiag commented on templates/footer.hbs
> +            <div>
Give this div a class name. A div by itself is not very explaining

2021-08-28 14:04 UTC, diegoamt requested changes
The Footer should be always included in the page instead of adding it as a component in the Components section of the Page Model.
This means we should need to add the Footer on 'page.hbs' after adding components: `{{{module footer}}}`

2021-09-09 21:22 UTC, camilomejiag approved these changes

2021-09-09 23:52 UTC, diegoamt approved these changes

2021-09-16 23:09 UTC, merged